### ISSUE TITLE
Image break if using nested routes

### ISSUE THREAD

**Issue by hmaesta** [xiphux/svimg#11]
Input:
```svelte
<Image src="picture.jpeg" />
```

Output:
```html
<img srcset="g/picture.111.jpeg 480w, g/picture.111.jpeg 500w" sizes="480px" width="480"/>
```

That's fine for a static website or root page, **but** it fails when using [nested routes in SvelteKit.](https://kit.svelte.dev/docs#routing)

---

For instance, imagine we are editing `src/pages/blog/posts/my-first-post.svelte`

With the current output...
- Browser will look for: `website.com/blog/post/my-first-post/g/picture.111.jpeg` ❌
- Instead of `website.com/g/picture.111.jpeg` ✅

`svimg` correct output should be:

```html
<img srcset="/g/picture.111.jpeg 480w, /g/picture.111.jpeg 500w" sizes="480px" width="480"/>
```

---

I created a [sandbox](https://codesandbox.io/s/angry-rgb-z2zhy?file=/src/routes/index.svelte), but it will work fine since Codesandbox uses a CDN and all images are served from absolute path – but download it and try to run locally.

**Comment by xiphux** [comment]
For what it's worth, your sandbox still works fine when downloaded locally, because directory/Index.svelte's url is http://localhost:3000/directory. so g/picture.111.jpg from there is still requesting http://localhost:3000/g/picture.111.jpg. It's only a problem if the url is nested more than that (eg directory/directory2/Index.svelte).

I'll take a look but I think this might need to be more nuanced than just assuming a root relative url, because that would be problematic for any svelte app hosted in a subdirectory and not the root of the domain.

**Comment by hmaesta** [comment]
> For what it's worth, your sandbox still works fine (...) only a problem if the url is nested more than that

_Whoops,_ that's right! But you got the point 😅

> I think this might need to be more nuanced than just assuming a root relative url

I totally agree. Maybe add a new variable to settings?

```js
imagePreprocessor({
   inputDir: 'static',
   outputDir: 'static/g',
   publicPath: '/g'
})```

**Comment by hmaesta** [comment]
> your sandbox still works fine when downloaded locally

Hey Chris! Kind of offtopic but... Do you still have a local copy of my sandbox? If yes, can you send me the `yarn.lock`? 
I set a new project and `sharp` is returning an error. More details here: https://github.com/sveltejs/kit/issues/1547#issuecomment-910683686

**Comment by hmaesta** [comment]
Hey Chris! 👋 

First of all, ignore my previous comment that you were probably notified by e-mail. I manage to rollback to a previous version and it's working now.

I am working on a new project and decided to use `svimg`. It was working great, until I deployed to production.

| a |   |
|---|---|
Local:
<img src="https://user-images.githubusercontent.com/741969/131748146-3c875b13-c417-4913-b7ad-3e4b9668b67f.gif" width="300" />

**Comment by xiphux** [comment]
Does it work better if you define the configuration closer to the way the documentation does? With the inputDir being the base static resource directory, the outputDir being a subdirectory of that, and the Image src relative to inputDir?

```javascript
 imagePreprocessor({
            inputDir: 'static',
            outputDir: 'static/optimized-images',
```

```html
<Image src="images/big-dogs.jpg" />
```

I wrote this somewhat Sapper-focused originally, and it's quite possible I'm making some assumptions in the code about the directory structure working this way...

**Comment by hmaesta** [comment]
That made the trick, @xiphux 👏 
[It's working as expected now.](https://sveltekit-svimg-test.netlify.app/) Thanks, once again.

–

Returning the focus to this issue, here some examples with nested routes:

- ✅ https://sveltekit-svimg-test.netlify.app/
- ✅ https://sveltekit-svimg-test.netlify.app/small-dogs
- ❌ https://sveltekit-svimg-test.netlify.app/small-dogs/ 
- ❌  https://sveltekit-svimg-test.netlify.app/sea/sea-lions

**Comment by hmaesta** [comment]
Another benefit of `publicPath`: it would allow using CDN in production.

```js
imagePreprocessor({
   inputDir: 'static',
   outputDir: 'static/g',
   publicPath: process.env.NODE_ENV === 'development' ? '/g/' : 'https://my-mirror-cdn.com/g/'
})

**Comment by xiphux** [comment]
Yeah - there are some cases that could be handled automatically (eg if the src is specified as root-relative with a leading slash, like you'd need to do for normal img tags in nested routes, preserve that after preprocessing since I don't think the leading slash is preserved right now), but I think it's likely that adding some sort of publicPath option would be good to allow more advanced use cases.
