### ISSUE TITLE
Placeholder image is always bigger than actual image

### ISSUE THREAD

**Issue by hmaesta** [xiphux/svimg#12]
For every image in every screen size, `img.placeholder` has a bigger height than `picture img.image`.
That generates a bottom blured padding.

<img src="https://user-images.githubusercontent.com/741969/131909396-8d8aab54-cc7e-45bc-9ca3-f826ed7708ce.png" width="500"/>

---

| img.placeholder | picture img.image |
|---|---|
| 381.63 px | 377.19 px |
| ![Screen Shot 2021-09-02 at 17 06 57](https://user-images.githubusercontent.com/741969/131909514-93477865-c067-43eb-b44c-30c72ef19602.png) | ![Screen Shot 2021-09-02 at 17 06 51](https://user-images.githubusercontent.com/741969/131909606-332259fd-d793-4c28-91fd-3f31cb85bd3b.png) |

---

- Demo: https://sveltekit-svimg-test.netlify.app/

**Comment by xiphux** [comment]
Looks like there's a very slight difference in the placeholder's aspect ratio, probably due to it being rounded to the nearest pixel when resizing. The browser appears to be using the image's slightly-off aspect ratio instead of the explicit width/height I've specified due to the fact that svimg is specifying the css `height: auto` which would take precedence.

Unfortunately it's not as easy as just removing the `height: auto`, because it appears that the Tailwind base you're using also sets `height: auto` globally on `img` tags, and the `aspect-ratio` css property only seems to fix the issue in Firefox and not Chrome, so I'll need to keep messing with it...

**Comment by hmaesta** [comment]
Fixed indeed. Thanks once again, Chris!
