### ISSUE TITLE
Path resolved relative to current page.

### ISSUE THREAD

**Issue by TheFoolishPupil** [xiphux/svimg#24]
Heya. I'm using your component in two different places: on the root-level photography page, and in markdown posts that are under `/blog/`. The paths resolved of the Images in the markdown are are prefixed with `/blog/`. So instead of `/static/images/xyz.jpeg` I get /blog/static/images/xyz.jpeg`. Is there a way to address this?
```
src
└── routes
    ├── blog
    │   ├── first.md
    │   └── second.md
    └── photography.svelte
```

**Comment by xiphux** [comment]
Are you using a framework (like SvelteKit)? What does your preprocessor configuration look like? How are you using svimg in markdown - are you using the `rehype-svimg` package or something else?

**Comment by TheFoolishPupil** [comment]
Hey there! I am indeed using sveltekit. My configuration can be see below. I am using [mdsvex](https://mdsvex.com), and with that I am importing the Image component directly in my markdown, as can also be seen below.

---
`svelte.config.js`
```js
import preprocess from "svelte-preprocess";

const config = {
  preprocess: [
    preprocess({
      postcss: true,
    mdsvex({
      extensions: [".md", ".svx"],
    }),
    imagePreprocessor({
      inputDir: "static/images",
      outputDir: "static/images/optimized",
      publicPath: "static/images/optimized",
      webp: true,
      avif: true,
    }),
  ],
  // Snip
};
```
---
`example-usage.md`
```md
<script>
    import Image from "svimg";
</script>

# This is markdown

<Image src="/r1.jpeg" />
```

**Comment by xiphux** [comment]
Is there a repro I could look at?

I'm not quite clear on what you're trying to do with the publicPath you're setting, but I'm guessing it might have to do with the fact that you're defining a relative publicPath, and I believe sveltekit resolves relative paths based on where the svelte component (/markdown) is - so since they live in /blog/, it thinks the public path is relative to /blog/. Do your images live in a static asset directory outside of the /blog/ hierarchy? If so, maybe you could try either:
* not defining a publicPath, since it looks like you're already using a root-relative url in your markdown file, or
* defining a root-relative publicPath starting with `/`

**Comment by TheFoolishPupil** [comment]
You were absolutely right. I was setting a relative path and was able to fix the issue by adding `\` to the `publicPath`. 👍
