### ISSUE TITLE
could we add support for parent div width identification?

### ISSUE THREAD

**Issue by ohbob** [xiphux/svimg#8]
Potentially could save a ton of bandwidth, if additionally calculate the width of the container instead of the window on the client. 

e.g. at this moment, the image will be the same in 50% screen size container or 100% container. 

You can check an example of how that works in a repo I made, but I would like to see this in yours as yours is more polished. 
repo - https://github.com/ohbob/svelte-responsive-images/
demo - https://svelte-responsive-images.nallus.com/

just don't check the npm, as i cannot update it at this moment, just check the code in image.svelte

**Comment by xiphux** [comment]
It should be doing that already... it was one of the motivations for starting the project in the first place instead of just going with something like svelte-image.

The component uses a ResizeObserver on the immediate parent div of the picture element to dynamically set the sizes attribute on the srcset. So the browser should know the exact width of the image it needs to download from the srcset.

(although browsers have some other things they'll factor in as well besides the width, such as the pixel density of the screen and whether they already have a higher resolution image from the srcset cached on disk that could just be downscaled).

**Comment by ohbob** [comment]
<section class="grid grid-cols-1">
<Image src="assets/one.jpg" />
</section>


<section class="grid grid-cols-3">
    <Image src="assets/one.jpg" />
    <Image src="assets/one.jpg" />
    <Image src="assets/one.jpg" />
</section>

What you think should be the outcome? should it do the same image or 2 different images? as the other container has 3 columns, it obviously should pick 1/3 less size picture right? Well, with not checking dynamically the parent container size, it will check for the window size. which leads to choosing the same image, thus, losing the benefits of bandwidth economy. 

as you see in this example, srcset uses only one size for the picture. 
![image](https://user-images.githubusercontent.com/47858537/120087732-1f523800-c0f3-11eb-9b22-2fae5c7bef8e.png)

Now let me show you the same code example from my repo. 

![image](https://user-images.githubusercontent.com/47858537/120087830-275ea780-c0f4-11eb-90b6-e720bce51216.png)

as you see here, we get the fullwidth version of one_1420.avif and the 1/3 version which is one_520.avif, the size difference is significat ans well 17.2kb vs 7.2kb. Hope that helps and clears out what i was meaning by that. If you need more information or don't understand my repo, you can hit me up on discord. Camo#8517

**Comment by xiphux** [comment]
The default behavior of srcset is to use the viewport size, unless you specify a `sizes` attribute... [sizes specifies the width of the slot the image will fill](https://css-tricks.com/sometimes-sizes-is-quite-important/) to chose an appropriate source from the srcset. And svimg is setting `sizes` based on the parent container div's width.

The reason your reproduction with svimg is downloading the larger image is because of your first grid with one column. The width of that grid and image is 1273px, which means the browser downloads the next larger image (g/one.d9015d2.* for 1920w). It doesn't need to download anything else for the 3-column grid because that grid uses the same srcset as the 1-column grid, and it can just use the larger 1920 image it already downloaded and downscale it from the cache for the 3 424px images (this is standard Chrome behavior), meaning it downloaded 20.8k to render all 4 images.

Since it seems like your component is modifying the srcset itself, the browser can't really figure out that the 3-column and 1-column images are the same picture because the srcsets differ (the 3-column grid is not aware of any sources greater than 420w). So it downloaded both one_1420.avif/1220w to render the 1-column grid and one_520.avif/420w to render the 3-column grid. So actually, it had to download 17.2k for one_1420.avif and 7.2k for one_520.avif for a total of 24.4k (which is more data than the one image svimg downloaded).

Do you see different results if you remove the 1-column grid from the example and test the 3-column grid in isolation (without cache)?

**Comment by ohbob** [comment]
Well, I've copied the one.jpg and renamed it to two.jpg, and placed it to the three columns, i see the same file size. 

![image](https://user-images.githubusercontent.com/47858537/120097811-3452b980-c13b-11eb-8cfc-c727eb53a984.png)

![image](https://user-images.githubusercontent.com/47858537/120097805-2f8e0580-c13b-11eb-83d6-3fa23bc2ff0c.png)

You can see the filesize only changes on Window resize, not the column parent div resize, as you are stating. That's what I was telling you about. I know this because matunya created svelte-image on my encouragement when svelte had nothing, and i have been extensivly testing a lot of image optimization and found out about this thing, which seemed odd.

**Comment by ohbob** [comment]
If you don't see this as a problem, let me give you a real-life example.
your resolution is 1920x1080. For a 30x30 image container, what image size would be downloaded? Exactly, largest available. 

![image](https://user-images.githubusercontent.com/47858537/120098311-e1c6cc80-c13d-11eb-87d5-ec1199516aa5.png)
![image](https://user-images.githubusercontent.com/47858537/120098314-e5f2ea00-c13d-11eb-8680-98bbe7df5851.png)

**Comment by xiphux** [comment]
I do see this as a problem, but your first reproduction wasn't really illustrating the issue correctly, so it looked as though it was working. (having a viewport-wide image in the repo was obscuring the issue)

It looks like there might be a race condition between when the `sizes` attribute is getting established by the ResizeObserver and when the browser starts downloading the srcset. So it seems like in some cases the browser begins downloading the srcset without any `sizes` attribute, and therefore assumes 100vw.

This seems like it might be a browser dependent timing bug. In particular, it looks like this actually works fine on Firefox (where I happen to do the majority of my development) - Firefox seems to fairly consistently establish the ResizeObserver's size and `sizes` attribute before downloading anything and therefore downloads the correct size. Chrome, on the other hand, seems to fairly consistently begin downloading the srcset before the ResizeObserver can establish its size and the `sizes` attribute, therefore downloading the viewport size.
